<?php	return array (
  0 => 
  array (
    'actor' => '克里斯·埃文斯 / 小罗伯特·唐尼 / 斯嘉丽·约翰逊 / 塞巴斯蒂安·斯坦 / 安东尼·麦凯 / ',
    'director' => '安东尼·卢素 / 乔·卢素',
    'has3D' => true,
    'hot' => 10021,
    'hot_planCount' => 168,
    'hot_priority' => 200,
    'intro' => '　　美国队长史蒂夫·罗杰斯（克里斯·埃文斯 Chris Evans 饰）带领着全新组建的复仇者联盟，继续维护世界和平。然而，一次执行任务时联盟成员不小心造成大量平民伤亡，从而激发政治压力，政府决定通过一套监管系统来管理和领导复仇者联盟。联盟内部因此分裂为两派：一方由史蒂夫· 罗杰斯领导，他主张维护成员自由，在免受政府干扰的情况下保护世界；另一方则追随托尼·斯塔克（小罗伯特·唐尼 Robert Downey Jr. 饰），他令人意外地决定支持政府的监管和责任制体系。神秘莫测的巴基（塞巴斯蒂安·斯坦 Sebastian Stan 饰）似乎成为内战的关键人物……',
    'minPrice' => '40.00',
    'minVipPrice' => '33.00',
    'movieId' => 387351,
    'movieLength' => 148,
    'movieName' => '美国队长3测试环境改一下影片名称一会改回去不行还得再加点才行',
    'movieType' => '动作 / 科幻 / 冒险',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14585373938960.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14603590107231.jpg',
    'publishTime' => '2016-05-06',
    'score' => '7.5',
  ),
  1 => 
  array (
    'actor' => '杰森·苏戴奇斯 / 乔什·加德 / 丹尼·麦克布耐德 / 玛娅·鲁道夫 / 西恩·潘 / 凯特·麦克',
    'director' => '克莱·凯蒂 / Fergal Reilly',
    'has3D' => true,
    'hot' => 35,
    'hot_planCount' => 307,
    'hot_priority' => 0,
    'intro' => '　　讲述一群不会飞的小鸟，挤在一座热带小岛上，和睦宁静。游戏中的几个经典形象成了影片的主角，分别是易怒的小鸟大红（杰森·苏戴奇斯 配音），速度小鸟恰克（乔什·盖德 配音）、炸弹（丹尼·麦克布耐德 配音）。当神秘的绿色小猪登陆岛屿时，小鸟们平静的生活被打破了。',
    'minPrice' => '40.00',
    'minVipPrice' => '33.00',
    'movieId' => 387646,
    'movieName' => '愤怒的小鸟',
    'movieType' => '喜剧 / 动作 / 动画',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14613141384466.jpg',
    'publishTime' => '2016-05-20',
    'score' => '8.0',
  ),
  2 => 
  array (
    'actor' => '崔维斯·费米尔 / 本·福斯特 / 托比·凯贝尔 / 宝拉·巴顿 / 多米尼克·库珀 / 鲁丝·内伽',
    'director' => '邓肯·琼斯',
    'has3D' => true,
    'hot' => 21,
    'hot_planCount' => 169,
    'hot_priority' => 0,
    'intro' => '　　根据暴雪娱乐公司的著名游戏改编，传奇影业的《魔兽》是一部空前紧张刺激的史诗历险巨制，由执导过《月球》和《源代码》的邓肯·琼斯编剧并导演。剧本由查尔斯·李维特（Charles Leavitt）共同编写。查尔斯·罗文（Charles Roven）、托马斯·图尔（Thomas Tull）、乔·贾希尼（Jon Jashni）和亚历克斯·加特纳（Alex Gartner）出任制片，斯图尔特·菲尼根（Stuart Fenegan）、吉莉安·谢尔（Jillian Share）和布兰特·欧康纳（Brent O’Connor）担任执行制片。',
    'minPrice' => '40.00',
    'minVipPrice' => '33.00',
    'movieId' => 18561,
    'movieLength' => 123,
    'movieName' => '魔兽',
    'movieType' => '动作 / 战争 / 奇幻 / 冒险',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14610304358071.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14624170423834.jpg',
    'publishTime' => '2016-06-08',
    'score' => '6.0',
  ),
  3 => 
  array (
    'actor' => '谢琳·伍德蕾 / 提奥·詹姆斯 / 杰夫·丹尼尔斯 / 奥克塔维亚·斯宾瑟 / 雷·史蒂文森 / 佐',
    'director' => '罗伯特·斯文克',
    'has2D' => true,
    'hot' => 19,
    'hot_planCount' => 143,
    'hot_priority' => 0,
    'intro' => '　　在推翻了派系制度之后，翠丝（谢琳·伍德蕾 Shailene Woodley 饰）与老四（提奥·詹姆斯 Theo James 饰）带领众人翻越了芝加哥的围墙来到全新世界。然而看似美好的新世界却隐藏着更大的杀机，翠丝与老四之间的信任也遭受到前所未有的考验。二人能否从阴谋中脱身并守住彼此？',
    'minPrice' => '40.00',
    'minVipPrice' => '33.00',
    'movieId' => 387580,
    'movieLength' => 121,
    'movieName' => '分歧者3：忠诚世界',
    'movieType' => '动作 / 爱情 / 科幻 / 冒险',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14610303428823.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14619008252292.jpg',
    'publishTime' => '2016-05-20',
    'score' => '8.0',
  ),
  4 => 
  array (
    'actor' => '约翰尼·德普 / 米娅·华希科沃斯卡 / 安妮·海瑟薇 / 海伦娜·伯翰·卡特 / 马特·卢卡斯 /',
    'director' => '詹姆斯·博宾',
    'has3D' => true,
    'hot' => 17,
    'hot_planCount' => 127,
    'hot_priority' => 0,
    'intro' => '　　爱丽丝（米娅·华希科沃斯卡 Mia Wasikowska 饰）为了拯救挚友疯帽子（约翰尼·德普 Johnny Depp 饰）而重返仙境，她与白皇后（安妮·海瑟薇 Anne Hathaway 饰）及一群老朋友一起，展开了一段璀璨华美、永生难忘的奇幻冒险。然而除了邪恶的红皇后之外，爱丽丝还要面对另一位劲敌——时间（萨莎·拜伦·科恩 Sacha Baron Cohen 饰），他是传说中无人能击败的角色！爱丽丝要如何才能扭转乾坤，拯救疯帽子和仙境世界？ <br> 　　影片改编自路易斯·卡罗尔广受好评的同名原作。',
    'minPrice' => '40.00',
    'minVipPrice' => '33.00',
    'movieId' => 387704,
    'movieLength' => 108,
    'movieName' => '爱丽丝梦游仙境2：镜中奇遇记',
    'movieType' => '奇幻 / 冒险',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14618256157011.jpg',
    'publishTime' => '2016-05-27',
    'score' => '8.0',
  ),
  5 => 
  array (
    'actor' => '陶泽如 / 李岷城 / 嵇波 / 胡先煦',
    'director' => '吴天明',
    'has2D' => true,
    'hot' => 13,
    'hot_planCount' => 91,
    'hot_priority' => 0,
    'intro' => '　　老一代唢呐艺人焦三爷是个外冷内热的老人，看起来严肃古板，其实心怀热血。影片表现了在社会变革、民心浮躁的年代里，新老两代唢呐艺人为了信念的坚守所产生的真挚的师徒情、父子情、兄弟情。',
    'minPrice' => '40.00',
    'minVipPrice' => '33.00',
    'movieId' => 385846,
    'movieLength' => 108,
    'movieName' => '百鸟朝凤',
    'movieType' => '剧情',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14598441122067.jpg',
    'pathHorizonS' => 'http://img.komovie.cn/poster/small/14279470997034.jpg',
    'pathSquare' => 'http://img.komovie.cn/poster/small_half/14279470982175.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14605304466588.jpg',
    'publishTime' => '2016-05-06',
    'score' => '8.0',
  ),
  6 => 
  array (
    'actor' => '刘亦菲 / 刘烨 / 余少群 / 黎明',
    'director' => '戴思杰',
    'has2D' => true,
    'hot' => 11,
    'hot_planCount' => 65,
    'hot_priority' => 0,
    'intro' => '　　法国女留学生埃尔莎在成都爱上了丝绸研究员、吹箫高手马荣，后又在巴黎与马的兄弟、纹身师建民之间产生情感。前者找到了一种符合他理想的蚕——夜孔雀，后者把蝶化的夜孔雀永远铭刻在艾尔莎的肌肤上。',
    'minPrice' => '40.00',
    'minVipPrice' => '33.00',
    'movieId' => 387551,
    'movieLength' => 90,
    'movieName' => '夜孔雀',
    'movieType' => '剧情 / 爱情',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14610303741787.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14605175661337.jpg',
    'publishTime' => '2016-05-20',
    'score' => '8.0',
  ),
);?>