<?php	return array (
  0 => 
  array (
    'actor' => '克里斯·埃文斯 / 小罗伯特·唐尼 / 斯嘉丽·约翰逊 / 塞巴斯蒂安·斯坦 / 安东尼·麦凯 / ',
    'director' => '安东尼·卢素 / 乔·卢素',
    'has3D' => true,
    'hot' => 10005,
    'hot_planCount' => 9,
    'hot_priority' => 200,
    'intro' => '　　美国队长史蒂夫·罗杰斯（克里斯·埃文斯 Chris Evans 饰）带领着全新组建的复仇者联盟，继续维护世界和平。然而，一次执行任务时联盟成员不小心造成大量平民伤亡，从而激发政治压力，政府决定通过一套监管系统来管理和领导复仇者联盟。联盟内部因此分裂为两派：一方由史蒂夫· 罗杰斯领导，他主张维护成员自由，在免受政府干扰的情况下保护世界；另一方则追随托尼·斯塔克（小罗伯特·唐尼 Robert Downey Jr. 饰），他令人意外地决定支持政府的监管和责任制体系。神秘莫测的巴基（塞巴斯蒂安·斯坦 Sebastian Stan 饰）似乎成为内战的关键人物……',
    'minPrice' => '60.00',
    'minVipPrice' => '53.00',
    'movieId' => 387351,
    'movieLength' => 148,
    'movieName' => '美国队长3测试环境改一下影片名称一会改回去不行还得再加点才行',
    'movieType' => '动作 / 科幻 / 冒险',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14585373938960.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14603590107231.jpg',
    'publishTime' => '2016-05-06',
    'score' => '7.5',
  ),
  1 => 
  array (
    'actor' => '汤唯 / 吴秀波 / 惠英红 / 秦沛 / 吴彦姝 / 颜卓灵 / 王志文 / 陆毅 / 祖峰 / ',
    'director' => '薛晓路',
    'has2D' => true,
    'hot' => 5005,
    'hot_planCount' => 7,
    'hot_priority' => 100,
    'intro' => '　　焦姣（汤唯 饰）15岁就随父亲移民到澳门，从此在赌城安家，并成为赌场公关。罗大牛（吴秀波 饰）则生活在洛杉矶，是一位房地产经纪人。姣爷和大牛通过一本书，巧合地通过手写书信的方式互相联系，两人从最初的完全陌生，到一步步敞开自己的心扉，逐渐进行心灵的交流，再到最后爱上对方。',
    'minPrice' => '50.00',
    'minVipPrice' => '43.00',
    'movieId' => 387318,
    'movieLength' => 131,
    'movieName' => '北京遇上西雅图2',
    'movieType' => '喜剧 / 爱情',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14579371083876.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14612264845028.jpg',
    'publishTime' => '2016-04-29',
    'score' => '8.8',
  ),
  2 => 
  array (
    'actor' => '黄晓明 / 徐峥 / 蒲巴甲 / 罗晋 / 汤镇业 / 锦荣 / 谭凯 / 姜超 / 赵亮 / 车晓',
    'director' => '霍建起',
    'has2D' => true,
    'hot' => 4755,
    'hot_planCount' => 13,
    'hot_priority' => 95,
    'intro' => '　　影片讲述历史上的唐朝高僧玄奘历时17年，不畏艰难险阻，前往天竺取经的传奇故事。大唐贞观盛世，年轻的玄奘法师（黄晓明 饰）为求佛法真谛冒死偷渡出境，一路上遭遇千难万阻，天灾人祸，却也深得民间疾苦。官兵围堵、徒弟背叛、埋身沙海、断水绝粮，玄奘法师一心求法，最终抵达印度，在印度弘扬善念静心修佛，等到从无遮大会辩论成功回国之时，已经是年逾五十的老人了。',
    'minPrice' => '40.00',
    'minVipPrice' => '33.00',
    'movieId' => 387178,
    'movieLength' => 120,
    'movieName' => '大唐玄奘',
    'movieType' => '历史',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14530965095684.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14618134874511.jpg',
    'publishTime' => '2016-04-29',
    'score' => '8.4',
  ),
  3 => 
  array (
    'actor' => '姚晨 / 唐嫣 / 郝蕾 / 郭富城 / 李晨 / 王一博 / 金圣柱 / 汤镇业 / 罗嘉良 / ',
    'director' => '张太维',
    'has2D' => true,
    'hot' => 4405,
    'hot_planCount' => 7,
    'hot_priority' => 88,
    'intro' => '　　这是一个讲述三个阶层不同性格不同的女人为金钱、家庭、地位共同淘金的故事。 <br> 　　留学生卢珍溪（姚晨 饰）在美国卖假包被驱逐回国，商场精英文清（郝蕾 饰）遭遇小三插足，灰姑娘顾巧音（唐嫣 饰）家庭贫寒只想嫁个有钱人。她们从一开始的死对头变成好闺蜜，并在事业导师孟晓骏（郭富城 饰）和卢珍溪的发小俊成(李晨 饰)的支持下，成为追求财富、爱情和地位的合伙人。她们短时间内取得巨大成功。不过好景不长，公司在市场激烈竞争下出现严重问题，陷入困局，同时三人的关系也出现破裂。面对困境，卢珍溪承受严峻考验的同时，为梦想和合伙人走出了坚定的一步……',
    'minPrice' => '38.00',
    'minVipPrice' => '31.00',
    'movieId' => 387328,
    'movieLength' => 101,
    'movieName' => '梦想合伙人',
    'movieType' => '剧情 / 爱情',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14579370764807.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14618223393505.jpg',
    'publishTime' => '2016-04-29',
    'score' => '8.3',
  ),
  4 => 
  array (
    'actor' => '崔维斯·费米尔 / 本·福斯特 / 托比·凯贝尔 / 宝拉·巴顿 / 多米尼克·库珀 / 鲁丝·内伽',
    'director' => '邓肯·琼斯',
    'has3D' => true,
    'hot' => 17,
    'hot_planCount' => 125,
    'hot_priority' => 0,
    'intro' => '　　根据暴雪娱乐公司的著名游戏改编，传奇影业的《魔兽》是一部空前紧张刺激的史诗历险巨制，由执导过《月球》和《源代码》的邓肯·琼斯编剧并导演。剧本由查尔斯·李维特（Charles Leavitt）共同编写。查尔斯·罗文（Charles Roven）、托马斯·图尔（Thomas Tull）、乔·贾希尼（Jon Jashni）和亚历克斯·加特纳（Alex Gartner）出任制片，斯图尔特·菲尼根（Stuart Fenegan）、吉莉安·谢尔（Jillian Share）和布兰特·欧康纳（Brent O’Connor）担任执行制片。',
    'minPrice' => '60.00',
    'minVipPrice' => '53.00',
    'movieId' => 18561,
    'movieLength' => 123,
    'movieName' => '魔兽',
    'movieType' => '动作 / 战争 / 奇幻 / 冒险',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14610304358071.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14624170423834.jpg',
    'publishTime' => '2016-06-08',
    'score' => '6.0',
  ),
  5 => 
  array (
    'actor' => '詹姆斯·麦卡沃伊 / 迈克尔·法斯宾德 / 詹妮弗·劳伦斯 / 尼古拉斯·霍尔特 / 奥斯卡·伊萨克',
    'director' => '布莱恩·辛格',
    'has3D' => true,
    'hot' => 11,
    'hot_planCount' => 65,
    'hot_priority' => 0,
    'intro' => '　　继漫威英雄系列巅峰之作《X战警：逆转未来》席卷全球之后，一手打造《X战警》系列的布莱恩辛格再度亲手执导，推出更大制作的《X战警：天启》。“天启”是漫威X战警世界里，能力最强大并且是史上首位变种人，自人类文明开始以来，便为世人当作天神来膜拜，他汲取多位变种人的超能力，演变成一位永生不死且无人能敌的超级变种人，历经数千年后，他再度觉醒，集结了多位强大的变种人意欲毁灭一切，重建世界秩序，当中包含失志的万磁王（迈克尔法斯宾德 饰）。当地球面临未知的巨大危机之际，瑞雯（詹妮弗劳伦斯 饰）在X教授（詹姆斯麦卡沃伊 饰）的协助之下，必须领导年轻的X战警们力抗这史上最强大的敌人，并扭转人类命运。',
    'minPrice' => '60.00',
    'minVipPrice' => '53.00',
    'movieId' => 387696,
    'movieName' => 'X战警：天启',
    'movieType' => '动作 / 科幻 / 奇幻 / 冒险',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14617432307798.jpg',
    'publishTime' => '2016-06-03',
    'score' => '8.0',
  ),
  6 => 
  array (
    'actor' => '约翰尼·德普 / 米娅·华希科沃斯卡 / 安妮·海瑟薇 / 海伦娜·伯翰·卡特 / 马特·卢卡斯 /',
    'director' => '詹姆斯·博宾',
    'has3D' => true,
    'hot' => 9,
    'hot_planCount' => 49,
    'hot_priority' => 0,
    'intro' => '　　爱丽丝（米娅·华希科沃斯卡 Mia Wasikowska 饰）为了拯救挚友疯帽子（约翰尼·德普 Johnny Depp 饰）而重返仙境，她与白皇后（安妮·海瑟薇 Anne Hathaway 饰）及一群老朋友一起，展开了一段璀璨华美、永生难忘的奇幻冒险。然而除了邪恶的红皇后之外，爱丽丝还要面对另一位劲敌——时间（萨莎·拜伦·科恩 Sacha Baron Cohen 饰），他是传说中无人能击败的角色！爱丽丝要如何才能扭转乾坤，拯救疯帽子和仙境世界？ <br> 　　影片改编自路易斯·卡罗尔广受好评的同名原作。',
    'minPrice' => '60.00',
    'minVipPrice' => '53.00',
    'movieId' => 387704,
    'movieLength' => 108,
    'movieName' => '爱丽丝梦游仙境2：镜中奇遇记',
    'movieType' => '奇幻 / 冒险',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14618256157011.jpg',
    'publishTime' => '2016-05-27',
    'score' => '8.0',
  ),
  7 => 
  array (
    'actor' => '杰森·苏戴奇斯 / 乔什·加德 / 丹尼·麦克布耐德 / 玛娅·鲁道夫 / 西恩·潘 / 凯特·麦克',
    'director' => '克莱·凯蒂 / Fergal Reilly',
    'has3D' => true,
    'hot' => 5,
    'hot_planCount' => 13,
    'hot_priority' => 0,
    'intro' => '　　讲述一群不会飞的小鸟，挤在一座热带小岛上，和睦宁静。游戏中的几个经典形象成了影片的主角，分别是易怒的小鸟大红（杰森·苏戴奇斯 配音），速度小鸟恰克（乔什·盖德 配音）、炸弹（丹尼·麦克布耐德 配音）。当神秘的绿色小猪登陆岛屿时，小鸟们平静的生活被打破了。',
    'minPrice' => '60.00',
    'minVipPrice' => '53.00',
    'movieId' => 387646,
    'movieName' => '愤怒的小鸟',
    'movieType' => '喜剧 / 动作 / 动画',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14613141384466.jpg',
    'publishTime' => '2016-05-20',
    'score' => '8.0',
  ),
  8 => 
  array (
    'actor' => '谢琳·伍德蕾 / 提奥·詹姆斯 / 杰夫·丹尼尔斯 / 奥克塔维亚·斯宾瑟 / 雷·史蒂文森 / 佐',
    'director' => '罗伯特·斯文克',
    'has2D' => true,
    'hot' => 5,
    'hot_planCount' => 9,
    'hot_priority' => 0,
    'intro' => '　　在推翻了派系制度之后，翠丝（谢琳·伍德蕾 Shailene Woodley 饰）与老四（提奥·詹姆斯 Theo James 饰）带领众人翻越了芝加哥的围墙来到全新世界。然而看似美好的新世界却隐藏着更大的杀机，翠丝与老四之间的信任也遭受到前所未有的考验。二人能否从阴谋中脱身并守住彼此？',
    'minPrice' => '50.00',
    'minVipPrice' => '43.00',
    'movieId' => 387580,
    'movieLength' => 121,
    'movieName' => '分歧者3：忠诚世界',
    'movieType' => '动作 / 爱情 / 科幻 / 冒险',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14610303428823.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14619008252292.jpg',
    'publishTime' => '2016-05-20',
    'score' => '8.0',
  ),
  9 => 
  array (
    'actor' => '刘亦菲 / 刘烨 / 余少群 / 黎明',
    'director' => '戴思杰',
    'has2D' => true,
    'hot' => 5,
    'hot_planCount' => 4,
    'hot_priority' => 0,
    'intro' => '　　法国女留学生埃尔莎在成都爱上了丝绸研究员、吹箫高手马荣，后又在巴黎与马的兄弟、纹身师建民之间产生情感。前者找到了一种符合他理想的蚕——夜孔雀，后者把蝶化的夜孔雀永远铭刻在艾尔莎的肌肤上。',
    'minPrice' => '50.00',
    'minVipPrice' => '43.00',
    'movieId' => 387551,
    'movieLength' => 90,
    'movieName' => '夜孔雀',
    'movieType' => '剧情 / 爱情',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14610303741787.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14605175661337.jpg',
    'publishTime' => '2016-05-20',
    'score' => '8.0',
  ),
  10 => 
  array (
    'actor' => '凯文·科斯特纳 / 加里·奥德曼 / 汤米·李·琼斯 / 瑞恩·雷诺兹 / 盖尔·加朵 / 爱丽丝·',
    'director' => '阿里尔·弗罗门',
    'has3D' => true,
    'hot' => 5,
    'hot_planCount' => 5,
    'hot_priority' => 0,
    'intro' => '　　一位知悉国家机密的CIA探员比利·波普（瑞恩·雷诺兹 Ryan Reynolds 饰）意外身亡，在弗兰克斯博士（汤米·李·琼斯 Tommy Lee Jones 饰）的协助下将其记忆与技能植入了一位极度危险且无法预测的罪犯杰里科·斯图尔特（凯文·科斯特纳 Kevin Costner 饰）身上，而探员贵格·威尔斯（加里·奥德曼 Gary Oldman 饰）必须靠这位不定时炸弹来摧毁企图攫取国家机密的犯罪组织。杰里科·斯图尔特为了救回换脑后渐渐爱上的比利·波普被胁迫的妻子和孩子，重新找回自己的生活，不得不在48小时的时间里，与犯罪组织展开殊死搏斗。',
    'minPrice' => '60.00',
    'minVipPrice' => '53.00',
    'movieId' => 387401,
    'movieLength' => 113,
    'movieName' => '超脑48小时',
    'movieType' => '剧情 / 动作 / 悬疑 / 惊悚 / 犯罪',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14591432031048.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14585266815716.jpg',
    'publishTime' => '2016-05-13',
    'score' => '8.0',
  ),
  11 => 
  array (
    'actor' => '陶泽如 / 李岷城 / 嵇波 / 胡先煦',
    'director' => '吴天明',
    'has2D' => true,
    'hot' => 5,
    'hot_planCount' => 9,
    'hot_priority' => 0,
    'intro' => '　　老一代唢呐艺人焦三爷是个外冷内热的老人，看起来严肃古板，其实心怀热血。影片表现了在社会变革、民心浮躁的年代里，新老两代唢呐艺人为了信念的坚守所产生的真挚的师徒情、父子情、兄弟情。',
    'minPrice' => '50.00',
    'minVipPrice' => '43.00',
    'movieId' => 385846,
    'movieLength' => 108,
    'movieName' => '百鸟朝凤',
    'movieType' => '剧情',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14598441122067.jpg',
    'pathHorizonS' => 'http://img.komovie.cn/poster/small/14279470997034.jpg',
    'pathSquare' => 'http://img.komovie.cn/poster/small_half/14279470982175.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14605304466588.jpg',
    'publishTime' => '2016-05-06',
    'score' => '8.0',
  ),
  12 => 
  array (
    'actor' => '温碧霞 / 陈锐 / 吴克羣 / 宋智孝 / 赵晨妍 / 吕良伟 / 李凤鸣 / 刘锡贤 / 多亮 ',
    'director' => '邓鉴泉 / 陈木川',
    'has2D' => true,
    'hot' => 4,
    'hot_planCount' => 1,
    'hot_priority' => 0,
    'intro' => '　　电影《708090》以“青春万 岁，梦想永恒”为主题，紧扣“商业重 组”的时代概念，讲述中国民营企业在 经济危机面前遭遇发展困惑与瓶颈这 一时代背景下，发生在70、80以及90 年代的三个主人公各自创业奋斗的故 事。',
    'minPrice' => '50.00',
    'minVipPrice' => '43.00',
    'movieId' => 387702,
    'movieLength' => 90,
    'movieName' => '708090之深圳恋歌',
    'movieType' => '剧情 / 爱情',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14618220411911.jpg',
    'publishTime' => '2016-05-20',
    'score' => '8.0',
  ),
  13 => 
  array (
    'actor' => '瑞恩·雷诺兹 / 本·金斯利 / 马修·古迪 / 娜塔丽·马丁内兹 / 米歇尔·道克瑞 / 德里克·',
    'director' => '塔西姆·辛',
    'has2D' => true,
    'hot' => 4,
    'hot_planCount' => 1,
    'hot_priority' => 0,
    'intro' => '　　曾在纽约建筑界享有极高声誉的富豪马丁·戴米恩（本·金斯利 Ben Kingsley 饰），而今饱受癌症折磨，不得不面对即将在半年后去世的事实。除此之外，他与女儿克莱尔的关系始终处于冰封状态，这令他不仅慨叹金钱的无力。不久前，马丁与菲尼克斯生物科技公司取得联系，对方声称使用最先进的脱换技术可以帮助马丁重获新生，简而言之就是将他的意识或者灵魂注入一具更加年轻健康的躯体内再生。经过慎重的考虑，马丁以爱德华·基德纳（瑞恩·雷诺兹 Ryan Reynolds 饰）的身份复活。此后的一段时间里，爱德华尽情享受重返青春的乐趣。 <br> 　　与此同时，这具陌生躯体背后所隐藏的秘密，则让他渐渐感到不安……',
    'minPrice' => '50.00',
    'minVipPrice' => '43.00',
    'movieId' => 387641,
    'movieLength' => 117,
    'movieName' => '幻体：续命游戏',
    'movieType' => '科幻 / 悬疑 / 惊悚',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14617415629502.jpg',
    'publishTime' => '2016-05-12',
    'score' => '8.0',
  ),
  14 => 
  array (
    'actor' => '浦蒲 / 李雯雯 / 方慧 / 孙祖君 / 刘天佐',
    'director' => '黄军',
    'has2D' => true,
    'hot' => 4,
    'hot_planCount' => 1,
    'hot_priority' => 0,
    'intro' => '　　神秘的深山旅社“丽园”，整形师于曼丽（浦蒲 饰），和因爱变性的学生韩真（方慧 饰）一起，以大学生梁敬涛（孙祖君 饰）、作家盛夏（李雯雯 饰）等为试验品，专研转基因换肤技术。而每个人身上都埋藏着转换身份的隐情。其中，于曼丽在一场车祸中失去爱人，自己也毁了容…… <br> 　　作为首部直面“整形风”的国产惊悚片， 《整形师·脸》以类型片的方式，通过整形惊悚、心理惊悚、人性惊悚等，“三重门”式递进深入时下美容整形现象的幽秘之处，令人不寒而栗。',
    'minPrice' => '50.00',
    'minVipPrice' => '43.00',
    'movieId' => 387515,
    'movieLength' => 101,
    'movieName' => '整形师·脸',
    'movieType' => '悬疑 / 惊悚',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14603659156452.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14620068812637.jpg',
    'publishTime' => '2016-05-20',
    'score' => '8.0',
  ),
  15 => 
  array (
    'actor' => '曹斐然 / 李铮 / 李奔',
    'director' => '姜军',
    'has2D' => true,
    'hot' => 4,
    'hot_planCount' => 1,
    'hot_priority' => 0,
    'intro' => '　　故事讲述了女孩梁倩一段离奇的经历。梁倩是奶奶从孤儿院里领养回家并一手带大的，长大后的梁倩叛逆不羁，她意外怀孕惹恼了奶奶，间接导致了奶奶脑溢血发作死去。奶奶死后留给梁倩一本记录其身世的笔记本，一份奇怪的遗嘱让她必须生下孩子，还有一个孤零零的空房子。 <br> 　　梁倩在忏悔中等待孩子的出生，但一切宁静都被一个陌生的女人打破了。这个女人租借了一个房间，每天都会给梁倩做好吃的，对梁倩和肚里的孩子照顾有加，可是慢慢地，梁倩发现了她种种怪异的举动，通过偷窥、跟踪，梁倩惊愕地发现这个女人房客原来是一个食婴人！最令人恐怖的是，这个女人的手正伸向梁倩肚中的孩子…… <br> 　　梁倩该怎么破？答案都在那个笔记本里。',
    'minPrice' => '50.00',
    'minVipPrice' => '43.00',
    'movieId' => 387500,
    'movieLength' => 99,
    'movieName' => '死亡笔记',
    'movieType' => '悬疑 / 惊悚 / 恐怖',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14619122432870.jpg',
    'publishTime' => '2016-05-20',
    'score' => '8.0',
  ),
  16 => 
  array (
    'actor' => '李抒航 / 王玥 / 邱云鹤',
    'director' => '唐永康',
    'has2D' => true,
    'hot' => 4,
    'hot_planCount' => 2,
    'hot_priority' => 0,
    'intro' => '　　青年实力派男演员李 抒航携北电素颜女神王玥双双步入婚 礼会场。同时到场的还有爆笑王子邱 云鹤。三人在影片中分饰三角，演绎 了一场属于九零后的别样爱情。',
    'minPrice' => '50.00',
    'minVipPrice' => '43.00',
    'movieId' => 387493,
    'movieName' => '在雨中',
    'movieType' => '爱情',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14603658571821.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14599304668708.jpg',
    'publishTime' => '2016-04-23',
    'score' => '8.0',
  ),
  17 => 
  array (
    'actor' => '陈柏霖 / 杨祐宁 / 蒋雯丽 / 秦沛 / 小茶',
    'director' => '忻钰坤 / 陈世杰 / 西瓦罗·孔萨库',
    'has2D' => true,
    'hot' => 4,
    'hot_planCount' => 1,
    'hot_priority' => 0,
    'intro' => '　　电影《再见，在也不见》由忻钰坤、陈世杰、西瓦罗·孔萨库联合执导，陈柏霖、蒋雯丽、杨祐宁、秦沛等两岸三地实力演员倾情演绎。电影讲述了一个关联的亲情，爱情，友情的情感故事。台湾文艺男神陈柏霖一人将人生所能经历的各种复杂情感体现的淋漓尽致。作为首部当选为台湾金马奖开幕影片的内地电影，该片着实令人期待。电影《再见，在也不见》也是新锐导演忻钰坤的最新力作。继《心迷宫》一炮而红后，忻钰坤以其冰冷写实的拍摄技巧以及细腻严谨的叙事风格获得了国内外影评人的一致盛赞。而这次参与《再见，在也不见》的联合指导，让人惊喜之余更大大提高了影片的期待值与关注度。',
    'minPrice' => '50.00',
    'minVipPrice' => '43.00',
    'movieId' => 387387,
    'movieLength' => 108,
    'movieName' => '再见，在也不见',
    'movieType' => '剧情 / 爱情 / 同性 / 家庭',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14585374186614.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14603593923167.jpg',
    'publishTime' => '2016-05-13',
    'score' => '8.0',
  ),
  18 => 
  array (
    'actor' => '何润东 / 李东学 / 夏梓桐 / 杨奇鸣 / 田原 / 赫子铭 / 宋宁 / 王往 / 黄天元',
    'director' => '阿甘',
    'has3D' => true,
    'hot' => 4,
    'hot_planCount' => 2,
    'hot_priority' => 0,
    'intro' => '　　哥哥王炳生（何润东 饰），弟弟陈铁金（李东学 饰），他们曾是相依为命、甘苦与共的兄弟。甚至哥哥炳生为弟弟铁金顶罪入狱十年，满身的伤疤与玩世不恭的态度是这十年的烙印，不变的却是兄弟之间的感情。不料在命运的捉弄下，两人在兵荒马乱的世界里失散，走上了不同的人生道路…… <br> 　　再度相逢时，曾经的患难兄弟已经势不两立。手足情深与家国信仰的冲突，令昔日兄弟成为生死之敌，最终展开了一场生死较量……',
    'minPrice' => '60.00',
    'minVipPrice' => '53.00',
    'movieId' => 386236,
    'movieLength' => 94,
    'movieName' => '钢刀',
    'movieType' => '剧情 / 动作',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14488670476087.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14586262223690.jpg',
    'publishTime' => '2016-05-20',
    'score' => '8.0',
  ),
);?>