<?php	return array (
  0 => 
  array (
    'actor' => '克里斯·埃文斯 / 小罗伯特·唐尼 / 斯嘉丽·约翰逊 / 塞巴斯蒂安·斯坦 / 安东尼·麦凯 / ',
    'director' => '安东尼·卢素 / 乔·卢素',
    'has3D' => true,
    'hot' => 10028,
    'hot_planCount' => 236,
    'hot_priority' => 200,
    'intro' => '　　美国队长史蒂夫·罗杰斯（克里斯·埃文斯 Chris Evans 饰）带领着全新组建的复仇者联盟，继续维护世界和平。然而，一次执行任务时联盟成员不小心造成大量平民伤亡，从而激发政治压力，政府决定通过一套监管系统来管理和领导复仇者联盟。联盟内部因此分裂为两派：一方由史蒂夫· 罗杰斯领导，他主张维护成员自由，在免受政府干扰的情况下保护世界；另一方则追随托尼·斯塔克（小罗伯特·唐尼 Robert Downey Jr. 饰），他令人意外地决定支持政府的监管和责任制体系。神秘莫测的巴基（塞巴斯蒂安·斯坦 Sebastian Stan 饰）似乎成为内战的关键人物……',
    'minPrice' => '30.00',
    'minVipPrice' => '25.90',
    'movieId' => 387351,
    'movieLength' => 148,
    'movieName' => '美国队长3测试环境改一下影片名称一会改回去不行还得再加点才行',
    'movieType' => '动作 / 科幻 / 冒险',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14585373938960.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14603590107231.jpg',
    'publishTime' => '2016-05-06',
    'score' => '7.5',
  ),
  1 => 
  array (
    'actor' => '杰森·苏戴奇斯 / 乔什·加德 / 丹尼·麦克布耐德 / 玛娅·鲁道夫 / 西恩·潘 / 凯特·麦克',
    'director' => '克莱·凯蒂 / Fergal Reilly',
    'has3D' => true,
    'hot' => 50,
    'hot_planCount' => 456,
    'hot_priority' => 0,
    'intro' => '　　讲述一群不会飞的小鸟，挤在一座热带小岛上，和睦宁静。游戏中的几个经典形象成了影片的主角，分别是易怒的小鸟大红（杰森·苏戴奇斯 配音），速度小鸟恰克（乔什·盖德 配音）、炸弹（丹尼·麦克布耐德 配音）。当神秘的绿色小猪登陆岛屿时，小鸟们平静的生活被打破了。',
    'minPrice' => '35.00',
    'minVipPrice' => '30.90',
    'movieId' => 387646,
    'movieName' => '愤怒的小鸟',
    'movieType' => '喜剧 / 动作 / 动画',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14613141384466.jpg',
    'publishTime' => '2016-05-20',
    'score' => '8.0',
  ),
  2 => 
  array (
    'actor' => '崔维斯·费米尔 / 本·福斯特 / 托比·凯贝尔 / 宝拉·巴顿 / 多米尼克·库珀 / 鲁丝·内伽',
    'director' => '邓肯·琼斯',
    'has3D' => true,
    'hot' => 33,
    'hot_planCount' => 289,
    'hot_priority' => 0,
    'intro' => '　　根据暴雪娱乐公司的著名游戏改编，传奇影业的《魔兽》是一部空前紧张刺激的史诗历险巨制，由执导过《月球》和《源代码》的邓肯·琼斯编剧并导演。剧本由查尔斯·李维特（Charles Leavitt）共同编写。查尔斯·罗文（Charles Roven）、托马斯·图尔（Thomas Tull）、乔·贾希尼（Jon Jashni）和亚历克斯·加特纳（Alex Gartner）出任制片，斯图尔特·菲尼根（Stuart Fenegan）、吉莉安·谢尔（Jillian Share）和布兰特·欧康纳（Brent O’Connor）担任执行制片。',
    'minPrice' => '30.00',
    'minVipPrice' => '25.90',
    'movieId' => 18561,
    'movieLength' => 123,
    'movieName' => '魔兽',
    'movieType' => '动作 / 战争 / 奇幻 / 冒险',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14610304358071.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14624170423834.jpg',
    'publishTime' => '2016-06-08',
    'score' => '6.0',
  ),
  3 => 
  array (
    'actor' => '谢琳·伍德蕾 / 提奥·詹姆斯 / 杰夫·丹尼尔斯 / 奥克塔维亚·斯宾瑟 / 雷·史蒂文森 / 佐',
    'director' => '罗伯特·斯文克',
    'has2D' => true,
    'hot' => 25,
    'hot_planCount' => 209,
    'hot_priority' => 0,
    'intro' => '　　在推翻了派系制度之后，翠丝（谢琳·伍德蕾 Shailene Woodley 饰）与老四（提奥·詹姆斯 Theo James 饰）带领众人翻越了芝加哥的围墙来到全新世界。然而看似美好的新世界却隐藏着更大的杀机，翠丝与老四之间的信任也遭受到前所未有的考验。二人能否从阴谋中脱身并守住彼此？',
    'minPrice' => '30.00',
    'minVipPrice' => '25.90',
    'movieId' => 387580,
    'movieLength' => 121,
    'movieName' => '分歧者3：忠诚世界',
    'movieType' => '动作 / 爱情 / 科幻 / 冒险',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14610303428823.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14619008252292.jpg',
    'publishTime' => '2016-05-20',
    'score' => '8.0',
  ),
  4 => 
  array (
    'actor' => '詹姆斯·麦卡沃伊 / 迈克尔·法斯宾德 / 詹妮弗·劳伦斯 / 尼古拉斯·霍尔特 / 奥斯卡·伊萨克',
    'director' => '布莱恩·辛格',
    'has3D' => true,
    'hot' => 21,
    'hot_planCount' => 172,
    'hot_priority' => 0,
    'intro' => '　　继漫威英雄系列巅峰之作《X战警：逆转未来》席卷全球之后，一手打造《X战警》系列的布莱恩辛格再度亲手执导，推出更大制作的《X战警：天启》。“天启”是漫威X战警世界里，能力最强大并且是史上首位变种人，自人类文明开始以来，便为世人当作天神来膜拜，他汲取多位变种人的超能力，演变成一位永生不死且无人能敌的超级变种人，历经数千年后，他再度觉醒，集结了多位强大的变种人意欲毁灭一切，重建世界秩序，当中包含失志的万磁王（迈克尔法斯宾德 饰）。当地球面临未知的巨大危机之际，瑞雯（詹妮弗劳伦斯 饰）在X教授（詹姆斯麦卡沃伊 饰）的协助之下，必须领导年轻的X战警们力抗这史上最强大的敌人，并扭转人类命运。',
    'minPrice' => '30.00',
    'minVipPrice' => '25.90',
    'movieId' => 387696,
    'movieName' => 'X战警：天启',
    'movieType' => '动作 / 科幻 / 奇幻 / 冒险',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14617432307798.jpg',
    'publishTime' => '2016-06-03',
    'score' => '8.0',
  ),
  5 => 
  array (
    'actor' => '约翰尼·德普 / 米娅·华希科沃斯卡 / 安妮·海瑟薇 / 海伦娜·伯翰·卡特 / 马特·卢卡斯 /',
    'director' => '詹姆斯·博宾',
    'has3D' => true,
    'hot' => 20,
    'hot_planCount' => 157,
    'hot_priority' => 0,
    'intro' => '　　爱丽丝（米娅·华希科沃斯卡 Mia Wasikowska 饰）为了拯救挚友疯帽子（约翰尼·德普 Johnny Depp 饰）而重返仙境，她与白皇后（安妮·海瑟薇 Anne Hathaway 饰）及一群老朋友一起，展开了一段璀璨华美、永生难忘的奇幻冒险。然而除了邪恶的红皇后之外，爱丽丝还要面对另一位劲敌——时间（萨莎·拜伦·科恩 Sacha Baron Cohen 饰），他是传说中无人能击败的角色！爱丽丝要如何才能扭转乾坤，拯救疯帽子和仙境世界？ <br> 　　影片改编自路易斯·卡罗尔广受好评的同名原作。',
    'minPrice' => '30.00',
    'minVipPrice' => '25.90',
    'movieId' => 387704,
    'movieLength' => 108,
    'movieName' => '爱丽丝梦游仙境2：镜中奇遇记',
    'movieType' => '奇幻 / 冒险',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14618256157011.jpg',
    'publishTime' => '2016-05-27',
    'score' => '8.0',
  ),
  6 => 
  array (
    'actor' => '陶泽如 / 李岷城 / 嵇波 / 胡先煦',
    'director' => '吴天明',
    'has2D' => true,
    'hot' => 18,
    'hot_planCount' => 138,
    'hot_priority' => 0,
    'intro' => '　　老一代唢呐艺人焦三爷是个外冷内热的老人，看起来严肃古板，其实心怀热血。影片表现了在社会变革、民心浮躁的年代里，新老两代唢呐艺人为了信念的坚守所产生的真挚的师徒情、父子情、兄弟情。',
    'minPrice' => '35.00',
    'minVipPrice' => '30.90',
    'movieId' => 385846,
    'movieLength' => 108,
    'movieName' => '百鸟朝凤',
    'movieType' => '剧情',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14598441122067.jpg',
    'pathHorizonS' => 'http://img.komovie.cn/poster/small/14279470997034.jpg',
    'pathSquare' => 'http://img.komovie.cn/poster/small_half/14279470982175.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14605304466588.jpg',
    'publishTime' => '2016-05-06',
    'score' => '8.0',
  ),
  7 => 
  array (
    'actor' => '刘亦菲 / 刘烨 / 余少群 / 黎明',
    'director' => '戴思杰',
    'has2D' => true,
    'hot' => 16,
    'hot_planCount' => 122,
    'hot_priority' => 0,
    'intro' => '　　法国女留学生埃尔莎在成都爱上了丝绸研究员、吹箫高手马荣，后又在巴黎与马的兄弟、纹身师建民之间产生情感。前者找到了一种符合他理想的蚕——夜孔雀，后者把蝶化的夜孔雀永远铭刻在艾尔莎的肌肤上。',
    'minPrice' => '35.00',
    'minVipPrice' => '30.90',
    'movieId' => 387551,
    'movieLength' => 90,
    'movieName' => '夜孔雀',
    'movieType' => '剧情 / 爱情',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14610303741787.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14605175661337.jpg',
    'publishTime' => '2016-05-20',
    'score' => '8.0',
  ),
  8 => 
  array (
    'actor' => '凯文·科斯特纳 / 加里·奥德曼 / 汤米·李·琼斯 / 瑞恩·雷诺兹 / 盖尔·加朵 / 爱丽丝·',
    'director' => '阿里尔·弗罗门',
    'has2D' => true,
    'has3D' => true,
    'hot' => 12,
    'hot_planCount' => 76,
    'hot_priority' => 0,
    'intro' => '　　一位知悉国家机密的CIA探员比利·波普（瑞恩·雷诺兹 Ryan Reynolds 饰）意外身亡，在弗兰克斯博士（汤米·李·琼斯 Tommy Lee Jones 饰）的协助下将其记忆与技能植入了一位极度危险且无法预测的罪犯杰里科·斯图尔特（凯文·科斯特纳 Kevin Costner 饰）身上，而探员贵格·威尔斯（加里·奥德曼 Gary Oldman 饰）必须靠这位不定时炸弹来摧毁企图攫取国家机密的犯罪组织。杰里科·斯图尔特为了救回换脑后渐渐爱上的比利·波普被胁迫的妻子和孩子，重新找回自己的生活，不得不在48小时的时间里，与犯罪组织展开殊死搏斗。',
    'minPrice' => '30.00',
    'minVipPrice' => '25.90',
    'movieId' => 387401,
    'movieLength' => 113,
    'movieName' => '超脑48小时',
    'movieType' => '剧情 / 动作 / 悬疑 / 惊悚 / 犯罪',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14591432031048.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14585266815716.jpg',
    'publishTime' => '2016-05-13',
    'score' => '8.0',
  ),
  9 => 
  array (
    'actor' => '瑞恩·雷诺兹 / 本·金斯利 / 马修·古迪 / 娜塔丽·马丁内兹 / 米歇尔·道克瑞 / 德里克·',
    'director' => '塔西姆·辛',
    'has2D' => true,
    'hot' => 6,
    'hot_planCount' => 18,
    'hot_priority' => 0,
    'intro' => '　　曾在纽约建筑界享有极高声誉的富豪马丁·戴米恩（本·金斯利 Ben Kingsley 饰），而今饱受癌症折磨，不得不面对即将在半年后去世的事实。除此之外，他与女儿克莱尔的关系始终处于冰封状态，这令他不仅慨叹金钱的无力。不久前，马丁与菲尼克斯生物科技公司取得联系，对方声称使用最先进的脱换技术可以帮助马丁重获新生，简而言之就是将他的意识或者灵魂注入一具更加年轻健康的躯体内再生。经过慎重的考虑，马丁以爱德华·基德纳（瑞恩·雷诺兹 Ryan Reynolds 饰）的身份复活。此后的一段时间里，爱德华尽情享受重返青春的乐趣。 <br> 　　与此同时，这具陌生躯体背后所隐藏的秘密，则让他渐渐感到不安……',
    'minPrice' => '25.00',
    'minVipPrice' => '20.90',
    'movieId' => 387641,
    'movieLength' => 117,
    'movieName' => '幻体：续命游戏',
    'movieType' => '科幻 / 悬疑 / 惊悚',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14617415629502.jpg',
    'publishTime' => '2016-05-12',
    'score' => '8.0',
  ),
);?>