<?php	return array (
  0 => 
  array (
    'actor' => '克里斯·埃文斯 / 小罗伯特·唐尼 / 斯嘉丽·约翰逊 / 塞巴斯蒂安·斯坦 / 安东尼·麦凯 / ',
    'director' => '安东尼·卢素 / 乔·卢素',
    'has2D' => true,
    'has3D' => true,
    'hot' => 10182,
    'hot_planCount' => 1771,
    'hot_priority' => 200,
    'intro' => '　　美国队长史蒂夫·罗杰斯（克里斯·埃文斯 Chris Evans 饰）带领着全新组建的复仇者联盟，继续维护世界和平。然而，一次执行任务时联盟成员不小心造成大量平民伤亡，从而激发政治压力，政府决定通过一套监管系统来管理和领导复仇者联盟。联盟内部因此分裂为两派：一方由史蒂夫· 罗杰斯领导，他主张维护成员自由，在免受政府干扰的情况下保护世界；另一方则追随托尼·斯塔克（小罗伯特·唐尼 Robert Downey Jr. 饰），他令人意外地决定支持政府的监管和责任制体系。神秘莫测的巴基（塞巴斯蒂安·斯坦 Sebastian Stan 饰）似乎成为内战的关键人物……',
    'minPrice' => '28.00',
    'minVipPrice' => '25.90',
    'movieId' => 387351,
    'movieLength' => 148,
    'movieName' => '美国队长3测试环境改一下影片名称一会改回去不行还得再加点才行',
    'movieType' => '动作 / 科幻 / 冒险',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14585373938960.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14603590107231.jpg',
    'publishTime' => '2016-05-06',
    'score' => '7.5',
  ),
  1 => 
  array (
    'actor' => '汤唯 / 吴秀波 / 惠英红 / 秦沛 / 吴彦姝 / 颜卓灵 / 王志文 / 陆毅 / 祖峰 / ',
    'director' => '薛晓路',
    'has2D' => true,
    'hot' => 5056,
    'hot_planCount' => 513,
    'hot_priority' => 100,
    'intro' => '　　焦姣（汤唯 饰）15岁就随父亲移民到澳门，从此在赌城安家，并成为赌场公关。罗大牛（吴秀波 饰）则生活在洛杉矶，是一位房地产经纪人。姣爷和大牛通过一本书，巧合地通过手写书信的方式互相联系，两人从最初的完全陌生，到一步步敞开自己的心扉，逐渐进行心灵的交流，再到最后爱上对方。',
    'minPrice' => '38.00',
    'minVipPrice' => '35.90',
    'movieId' => 387318,
    'movieLength' => 131,
    'movieName' => '北京遇上西雅图2',
    'movieType' => '喜剧 / 爱情',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14579371083876.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14612264845028.jpg',
    'publishTime' => '2016-04-29',
    'score' => '8.8',
  ),
  2 => 
  array (
    'actor' => '黄晓明 / 徐峥 / 蒲巴甲 / 罗晋 / 汤镇业 / 锦荣 / 谭凯 / 姜超 / 赵亮 / 车晓',
    'director' => '霍建起',
    'has2D' => true,
    'hot' => 4755,
    'hot_planCount' => 6,
    'hot_priority' => 95,
    'intro' => '　　影片讲述历史上的唐朝高僧玄奘历时17年，不畏艰难险阻，前往天竺取经的传奇故事。大唐贞观盛世，年轻的玄奘法师（黄晓明 饰）为求佛法真谛冒死偷渡出境，一路上遭遇千难万阻，天灾人祸，却也深得民间疾苦。官兵围堵、徒弟背叛、埋身沙海、断水绝粮，玄奘法师一心求法，最终抵达印度，在印度弘扬善念静心修佛，等到从无遮大会辩论成功回国之时，已经是年逾五十的老人了。',
    'minPrice' => '55.00',
    'minVipPrice' => '48.00',
    'movieId' => 387178,
    'movieLength' => 120,
    'movieName' => '大唐玄奘',
    'movieType' => '历史',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14530965095684.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14618134874511.jpg',
    'publishTime' => '2016-04-29',
    'score' => '8.4',
  ),
  3 => 
  array (
    'actor' => '崔维斯·费米尔 / 本·福斯特 / 托比·凯贝尔 / 宝拉·巴顿 / 多米尼克·库珀 / 鲁丝·内伽',
    'director' => '邓肯·琼斯',
    'has2D' => true,
    'has3D' => true,
    'hot' => 937,
    'hot_planCount' => 9291,
    'hot_priority' => 0,
    'intro' => '　　根据暴雪娱乐公司的著名游戏改编，传奇影业的《魔兽》是一部空前紧张刺激的史诗历险巨制，由执导过《月球》和《源代码》的邓肯·琼斯编剧并导演。剧本由查尔斯·李维特（Charles Leavitt）共同编写。查尔斯·罗文（Charles Roven）、托马斯·图尔（Thomas Tull）、乔·贾希尼（Jon Jashni）和亚历克斯·加特纳（Alex Gartner）出任制片，斯图尔特·菲尼根（Stuart Fenegan）、吉莉安·谢尔（Jillian Share）和布兰特·欧康纳（Brent O’Connor）担任执行制片。',
    'minPrice' => '28.00',
    'minVipPrice' => '25.90',
    'movieId' => 18561,
    'movieLength' => 123,
    'movieName' => '魔兽',
    'movieType' => '动作 / 战争 / 奇幻 / 冒险',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14610304358071.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14624170423834.jpg',
    'publishTime' => '2016-06-08',
    'score' => '6.0',
  ),
  4 => 
  array (
    'actor' => '詹姆斯·麦卡沃伊 / 迈克尔·法斯宾德 / 詹妮弗·劳伦斯 / 尼古拉斯·霍尔特 / 奥斯卡·伊萨克',
    'director' => '布莱恩·辛格',
    'has2D' => true,
    'has3D' => true,
    'hot' => 698,
    'hot_planCount' => 6896,
    'hot_priority' => 0,
    'intro' => '　　继漫威英雄系列巅峰之作《X战警：逆转未来》席卷全球之后，一手打造《X战警》系列的布莱恩辛格再度亲手执导，推出更大制作的《X战警：天启》。“天启”是漫威X战警世界里，能力最强大并且是史上首位变种人，自人类文明开始以来，便为世人当作天神来膜拜，他汲取多位变种人的超能力，演变成一位永生不死且无人能敌的超级变种人，历经数千年后，他再度觉醒，集结了多位强大的变种人意欲毁灭一切，重建世界秩序，当中包含失志的万磁王（迈克尔法斯宾德 饰）。当地球面临未知的巨大危机之际，瑞雯（詹妮弗劳伦斯 饰）在X教授（詹姆斯麦卡沃伊 饰）的协助之下，必须领导年轻的X战警们力抗这史上最强大的敌人，并扭转人类命运。',
    'minPrice' => '28.00',
    'minVipPrice' => '25.90',
    'movieId' => 387696,
    'movieName' => 'X战警：天启',
    'movieType' => '动作 / 科幻 / 奇幻 / 冒险',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14617432307798.jpg',
    'publishTime' => '2016-06-03',
    'score' => '8.0',
  ),
  5 => 
  array (
    'actor' => '约翰尼·德普 / 米娅·华希科沃斯卡 / 安妮·海瑟薇 / 海伦娜·伯翰·卡特 / 马特·卢卡斯 /',
    'director' => '詹姆斯·博宾',
    'has2D' => true,
    'has3D' => true,
    'hot' => 611,
    'hot_planCount' => 6034,
    'hot_priority' => 0,
    'intro' => '　　爱丽丝（米娅·华希科沃斯卡 Mia Wasikowska 饰）为了拯救挚友疯帽子（约翰尼·德普 Johnny Depp 饰）而重返仙境，她与白皇后（安妮·海瑟薇 Anne Hathaway 饰）及一群老朋友一起，展开了一段璀璨华美、永生难忘的奇幻冒险。然而除了邪恶的红皇后之外，爱丽丝还要面对另一位劲敌——时间（萨莎·拜伦·科恩 Sacha Baron Cohen 饰），他是传说中无人能击败的角色！爱丽丝要如何才能扭转乾坤，拯救疯帽子和仙境世界？ <br> 　　影片改编自路易斯·卡罗尔广受好评的同名原作。',
    'minPrice' => '28.00',
    'minVipPrice' => '25.90',
    'movieId' => 387704,
    'movieLength' => 108,
    'movieName' => '爱丽丝梦游仙境2：镜中奇遇记',
    'movieType' => '奇幻 / 冒险',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14618256157011.jpg',
    'publishTime' => '2016-05-27',
    'score' => '8.0',
  ),
  6 => 
  array (
    'actor' => '杰森·苏戴奇斯 / 乔什·加德 / 丹尼·麦克布耐德 / 玛娅·鲁道夫 / 西恩·潘 / 凯特·麦克',
    'director' => '克莱·凯蒂 / Fergal Reilly',
    'has2D' => true,
    'has3D' => true,
    'hot' => 544,
    'hot_planCount' => 5361,
    'hot_priority' => 0,
    'intro' => '　　讲述一群不会飞的小鸟，挤在一座热带小岛上，和睦宁静。游戏中的几个经典形象成了影片的主角，分别是易怒的小鸟大红（杰森·苏戴奇斯 配音），速度小鸟恰克（乔什·盖德 配音）、炸弹（丹尼·麦克布耐德 配音）。当神秘的绿色小猪登陆岛屿时，小鸟们平静的生活被打破了。',
    'minPrice' => '28.00',
    'minVipPrice' => '25.90',
    'movieId' => 387646,
    'movieName' => '愤怒的小鸟',
    'movieType' => '喜剧 / 动作 / 动画',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14613141384466.jpg',
    'publishTime' => '2016-05-20',
    'score' => '8.0',
  ),
  7 => 
  array (
    'actor' => '谢琳·伍德蕾 / 提奥·詹姆斯 / 杰夫·丹尼尔斯 / 奥克塔维亚·斯宾瑟 / 雷·史蒂文森 / 佐',
    'director' => '罗伯特·斯文克',
    'has2D' => true,
    'hot' => 145,
    'hot_planCount' => 1399,
    'hot_priority' => 0,
    'intro' => '　　在推翻了派系制度之后，翠丝（谢琳·伍德蕾 Shailene Woodley 饰）与老四（提奥·詹姆斯 Theo James 饰）带领众人翻越了芝加哥的围墙来到全新世界。然而看似美好的新世界却隐藏着更大的杀机，翠丝与老四之间的信任也遭受到前所未有的考验。二人能否从阴谋中脱身并守住彼此？',
    'minPrice' => '23.00',
    'minVipPrice' => '20.90',
    'movieId' => 387580,
    'movieLength' => 121,
    'movieName' => '分歧者3：忠诚世界',
    'movieType' => '动作 / 爱情 / 科幻 / 冒险',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14610303428823.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14619008252292.jpg',
    'publishTime' => '2016-05-20',
    'score' => '8.0',
  ),
  8 => 
  array (
    'actor' => '陶泽如 / 李岷城 / 嵇波 / 胡先煦',
    'director' => '吴天明',
    'has2D' => true,
    'hot' => 96,
    'hot_planCount' => 914,
    'hot_priority' => 0,
    'intro' => '　　老一代唢呐艺人焦三爷是个外冷内热的老人，看起来严肃古板，其实心怀热血。影片表现了在社会变革、民心浮躁的年代里，新老两代唢呐艺人为了信念的坚守所产生的真挚的师徒情、父子情、兄弟情。',
    'minPrice' => '28.00',
    'minVipPrice' => '25.90',
    'movieId' => 385846,
    'movieLength' => 108,
    'movieName' => '百鸟朝凤',
    'movieType' => '剧情',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14598441122067.jpg',
    'pathHorizonS' => 'http://img.komovie.cn/poster/small/14279470997034.jpg',
    'pathSquare' => 'http://img.komovie.cn/poster/small_half/14279470982175.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14605304466588.jpg',
    'publishTime' => '2016-05-06',
    'score' => '8.0',
  ),
  9 => 
  array (
    'actor' => '祖晴 / 明婧 / 小玉 / 蒋林辰 / 李晶 / 黄珊珊 / 毛毛 / 小马 / 齐冀宁 / 马瑞',
    'director' => '杨劲松 / 梁董龙 / 刘平劼 / 陆伟',
    'has2D' => true,
    'hot' => 63,
    'hot_planCount' => 583,
    'hot_priority' => 0,
    'intro' => '　　出品单位: 广州爱动影视科技有限公司 <br> 　　吉星是水果村的一个小橘子，梦想成为水果英雄。一天，恶虫出现并袭击水果村！吉星和他的朋友榴星与美蕉在与恶虫的战斗中，各方都得到了成长，终于被封为“水果英雄”！最后他们打败了恶虫大王，为水果村村迎来和平……',
    'minPrice' => '25.00',
    'minVipPrice' => '23.00',
    'movieId' => 387400,
    'movieName' => '水果宝贝之水果总动员',
    'movieType' => '喜剧 / 动画',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14598440574724.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14582068234640.jpg',
    'publishTime' => '2016-06-01',
    'score' => '8.0',
  ),
  10 => 
  array (
    'actor' => '黄莺 / 安琪 / 李正翔 / 张欣 / 姜玉玲',
    'director' => '(小)徐克',
    'has2D' => true,
    'has3D' => true,
    'hot' => 40,
    'hot_planCount' => 355,
    'hot_priority' => 0,
    'intro' => '　　地球籍小学生小雨一直想成为朋友中的领袖，和绿林星球的小伙伴们一起努力，共同完成一个任务。一次意外，妈妈陷入困境，如果不在有限的时间内完成拯救，妈妈将永远回不来。为了救回妈妈，小雨带领她绿林星球的朋友组成的团队来到糖果世界。 <br> 　　原本就是临时拼凑起来的团队，在生性固执的小雨的带领下，团队很快陷入糖果世界主人咕噜的阴谋中。而心焦如煎的小雨却不顾团队成员的阻拦，试图以一己之力挽救局势，但这只能让她滑进咕噜为之设计的深渊。 <br> 　　跌入低谷后，小雨终于领悟了“信任”才是友谊的关键，但时间已经所剩无几……最终，她能成功的扭转局势、拯救大家脱困吗？',
    'minPrice' => '33.00',
    'minVipPrice' => '30.90',
    'movieId' => 386209,
    'movieLength' => 90,
    'movieName' => '糖果世界大冒险 ',
    'movieType' => '动画 / 奇幻 / 冒险',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14345201574021.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14338291609811.jpg',
    'publishTime' => '2016-05-27',
    'score' => '8.0',
  ),
  11 => 
  array (
    'actor' => '凯文·科斯特纳 / 加里·奥德曼 / 汤米·李·琼斯 / 瑞恩·雷诺兹 / 盖尔·加朵 / 爱丽丝·',
    'director' => '阿里尔·弗罗门',
    'has2D' => true,
    'has3D' => true,
    'hot' => 34,
    'hot_planCount' => 300,
    'hot_priority' => 0,
    'intro' => '　　一位知悉国家机密的CIA探员比利·波普（瑞恩·雷诺兹 Ryan Reynolds 饰）意外身亡，在弗兰克斯博士（汤米·李·琼斯 Tommy Lee Jones 饰）的协助下将其记忆与技能植入了一位极度危险且无法预测的罪犯杰里科·斯图尔特（凯文·科斯特纳 Kevin Costner 饰）身上，而探员贵格·威尔斯（加里·奥德曼 Gary Oldman 饰）必须靠这位不定时炸弹来摧毁企图攫取国家机密的犯罪组织。杰里科·斯图尔特为了救回换脑后渐渐爱上的比利·波普被胁迫的妻子和孩子，重新找回自己的生活，不得不在48小时的时间里，与犯罪组织展开殊死搏斗。',
    'minPrice' => '30.00',
    'minVipPrice' => '28.00',
    'movieId' => 387401,
    'movieLength' => 113,
    'movieName' => '超脑48小时',
    'movieType' => '剧情 / 动作 / 悬疑 / 惊悚 / 犯罪',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14591432031048.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14585266815716.jpg',
    'publishTime' => '2016-05-13',
    'score' => '8.0',
  ),
  12 => 
  array (
    'actor' => '雷佳音 / 夏梓桐 / 李菁 / 孙宁 / 何云伟',
    'director' => '朴裕焕',
    'has2D' => true,
    'hot' => 23,
    'hot_planCount' => 184,
    'hot_priority' => 0,
    'intro' => '　　繁华都市的边缘地带有一栋老旧而神秘的公寓，里面居住着形形色色奇怪的人，有“高帅穷”的落魄小律师（雷佳音 饰）、有倔强的90后年轻漂亮女孩（夏梓桐 饰）、有惯于溜门撬锁的蠢贼（李菁 饰），更有黑社会老大（李彧 饰）和他的美艳性感情妇（孙宁 饰）以及假药小贩（何云伟 饰）等。 <br> 　　一个山雨欲来的夜里，就在这样的公寓里，突如其来多出了一具尸体……到底是谁杀了这个被所有人恨之入骨的男人？是被骗去万贯家财的他？还是被欺骗强暴了的她？抑或一直被人踩在头上的他？围绕着这具让所有人都惊慌不已的尸体，有人惊慌失措准备逃之夭夭，有人面色镇定承认杀人罪行，有人偷梁换柱企图制造自杀现场，有人咬牙切齿主动提出埋尸……在一天一夜之间各色人等都历经了一场终身难忘的记忆。而当谁是凶手的真相貌似“盖棺定论”时，意外的结局反转，让所有人都瞠目结舌……',
    'minPrice' => '30.00',
    'minVipPrice' => '28.00',
    'movieId' => 387323,
    'movieLength' => 90,
    'movieName' => '记忆碎片',
    'movieType' => '喜剧 / 悬疑',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14610304049172.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14619098114227.jpg',
    'publishTime' => '2016-05-27',
    'score' => '8.0',
  ),
  13 => 
  array (
    'actor' => '刘亦菲 / 刘烨 / 余少群 / 黎明',
    'director' => '戴思杰',
    'has2D' => true,
    'hot' => 14,
    'hot_planCount' => 100,
    'hot_priority' => 0,
    'intro' => '　　法国女留学生埃尔莎在成都爱上了丝绸研究员、吹箫高手马荣，后又在巴黎与马的兄弟、纹身师建民之间产生情感。前者找到了一种符合他理想的蚕——夜孔雀，后者把蝶化的夜孔雀永远铭刻在艾尔莎的肌肤上。',
    'minPrice' => '33.00',
    'minVipPrice' => '30.90',
    'movieId' => 387551,
    'movieLength' => 90,
    'movieName' => '夜孔雀',
    'movieType' => '剧情 / 爱情',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14610303741787.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14605175661337.jpg',
    'publishTime' => '2016-05-20',
    'score' => '8.0',
  ),
  14 => 
  array (
    'actor' => '胡严彦 / 刘沛 / 李晶 / 戴逸 / 张金玲 / 蔡丹 / 泽飞 / 李明 / 毛毛',
    'director' => '孟文龙 / 管霄超 / 汤华宝',
    'has2D' => true,
    'hot' => 12,
    'hot_planCount' => 74,
    'hot_priority' => 0,
    'intro' => '　　在遥远的宇宙中，一颗叫做布兰星的星球，居住着金木水火土五大蚂蚁神族，心怀和平梦想，蚂蚁皇后派出五大神族的精英：金童童、木吞吞、水灵灵、火聪聪、土豆豆，带着拥有五常文化的定界天碑，欲将仁、义、礼、智、信传扬宇宙，却在星际穿梭途中遭遇黑蚂蚁兄弟雷震震和风小小破坏，导致组成定界天碑的五常灵珠散落地球世界各地。为了找回灵珠，小蚂蚁开始了追寻梦想的环球冒险，在世界各地展开了一场又一场奇幻萌趣的争夺。',
    'minPrice' => '33.00',
    'minVipPrice' => '30.90',
    'movieId' => 387737,
    'movieLength' => 90,
    'movieName' => '小蚂蚁之环球大冒险',
    'movieType' => '喜剧 / 动画 / 冒险',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14623478884383.jpg',
    'publishTime' => '2016-05-27',
    'score' => '8.0',
  ),
  15 => 
  array (
    'actor' => '曹斐然 / 李铮 / 李奔',
    'director' => '姜军',
    'has2D' => true,
    'hot' => 8,
    'hot_planCount' => 34,
    'hot_priority' => 0,
    'intro' => '　　故事讲述了女孩梁倩一段离奇的经历。梁倩是奶奶从孤儿院里领养回家并一手带大的，长大后的梁倩叛逆不羁，她意外怀孕惹恼了奶奶，间接导致了奶奶脑溢血发作死去。奶奶死后留给梁倩一本记录其身世的笔记本，一份奇怪的遗嘱让她必须生下孩子，还有一个孤零零的空房子。 <br> 　　梁倩在忏悔中等待孩子的出生，但一切宁静都被一个陌生的女人打破了。这个女人租借了一个房间，每天都会给梁倩做好吃的，对梁倩和肚里的孩子照顾有加，可是慢慢地，梁倩发现了她种种怪异的举动，通过偷窥、跟踪，梁倩惊愕地发现这个女人房客原来是一个食婴人！最令人恐怖的是，这个女人的手正伸向梁倩肚中的孩子…… <br> 　　梁倩该怎么破？答案都在那个笔记本里。',
    'minPrice' => '40.00',
    'minVipPrice' => '33.00',
    'movieId' => 387500,
    'movieLength' => 99,
    'movieName' => '死亡笔记',
    'movieType' => '悬疑 / 惊悚 / 恐怖',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14619122432870.jpg',
    'publishTime' => '2016-05-20',
    'score' => '8.0',
  ),
  16 => 
  array (
    'actor' => '瑞恩·雷诺兹 / 本·金斯利 / 马修·古迪 / 娜塔丽·马丁内兹 / 米歇尔·道克瑞 / 德里克·',
    'director' => '塔西姆·辛',
    'has2D' => true,
    'hot' => 6,
    'hot_planCount' => 15,
    'hot_priority' => 0,
    'intro' => '　　曾在纽约建筑界享有极高声誉的富豪马丁·戴米恩（本·金斯利 Ben Kingsley 饰），而今饱受癌症折磨，不得不面对即将在半年后去世的事实。除此之外，他与女儿克莱尔的关系始终处于冰封状态，这令他不仅慨叹金钱的无力。不久前，马丁与菲尼克斯生物科技公司取得联系，对方声称使用最先进的脱换技术可以帮助马丁重获新生，简而言之就是将他的意识或者灵魂注入一具更加年轻健康的躯体内再生。经过慎重的考虑，马丁以爱德华·基德纳（瑞恩·雷诺兹 Ryan Reynolds 饰）的身份复活。此后的一段时间里，爱德华尽情享受重返青春的乐趣。 <br> 　　与此同时，这具陌生躯体背后所隐藏的秘密，则让他渐渐感到不安……',
    'minPrice' => '30.00',
    'minVipPrice' => '28.00',
    'movieId' => 387641,
    'movieLength' => 117,
    'movieName' => '幻体：续命游戏',
    'movieType' => '科幻 / 悬疑 / 惊悚',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14617415629502.jpg',
    'publishTime' => '2016-05-12',
    'score' => '8.0',
  ),
  17 => 
  array (
    'actor' => '徐洁儿 / 陈炳强 / 陈欢',
    'director' => '麦子',
    'has2D' => true,
    'hot' => 6,
    'hot_planCount' => 15,
    'hot_priority' => 0,
    'intro' => '　　电影《死亡游戏》主要讲述了一档旨在帮助沉迷鬼魇的女性走出困境的真人秀节目《凶灵实录》，故事内容别出心裁，情节设置恐怖烧脑。',
    'minPrice' => '45.00',
    'minVipPrice' => '38.00',
    'movieId' => 387438,
    'movieName' => '死亡游戏',
    'movieType' => '惊悚 / 恐怖',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14619160048568.jpg',
    'publishTime' => '2016-06-08',
    'score' => '8.0',
  ),
  18 => 
  array (
    'actor' => '浦蒲 / 李雯雯 / 方慧 / 孙祖君 / 刘天佐',
    'director' => '黄军',
    'has2D' => true,
    'hot' => 5,
    'hot_planCount' => 6,
    'hot_priority' => 0,
    'intro' => '　　神秘的深山旅社“丽园”，整形师于曼丽（浦蒲 饰），和因爱变性的学生韩真（方慧 饰）一起，以大学生梁敬涛（孙祖君 饰）、作家盛夏（李雯雯 饰）等为试验品，专研转基因换肤技术。而每个人身上都埋藏着转换身份的隐情。其中，于曼丽在一场车祸中失去爱人，自己也毁了容…… <br> 　　作为首部直面“整形风”的国产惊悚片， 《整形师·脸》以类型片的方式，通过整形惊悚、心理惊悚、人性惊悚等，“三重门”式递进深入时下美容整形现象的幽秘之处，令人不寒而栗。',
    'minPrice' => '40.00',
    'minVipPrice' => '33.00',
    'movieId' => 387515,
    'movieLength' => 101,
    'movieName' => '整形师·脸',
    'movieType' => '悬疑 / 惊悚',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14603659156452.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14620068812637.jpg',
    'publishTime' => '2016-05-20',
    'score' => '8.0',
  ),
  19 => 
  array (
    'actor' => '雷佳 / 张英席 / 高鹏 / 钱治国 / 巨有燕 / 王婷 / 赵阳 / 武猛 / 常通 / 刘海',
    'director' => '侯克明',
    'has2D' => true,
    'hot' => 5,
    'hot_planCount' => 6,
    'hot_priority' => 0,
    'intro' => '　　佃农杨白劳（高鹏 饰）与女儿喜儿（雷佳 饰）相依为命，喜儿与同村青年农民大春（张英席 饰）相爱。杨白劳因生活所迫向恶霸地主黄世仁（武猛 饰）借了高利贷，之后外出逃债。在除夕之夜杨白劳偷偷回家。黄世仁闻讯后强迫杨白劳卖女顶债，杨白劳喝做豆腐用的卤水自杀。喜儿被抢进黄家，遭黄世仁奸污，逃入深山，头发全白。两年后，大春随八路 军回乡，在山洞里找到喜儿，替她申冤雪恨...',
    'minPrice' => '43.00',
    'minVipPrice' => '40.90',
    'movieId' => 387444,
    'movieLength' => 122,
    'movieName' => '白毛女',
    'movieType' => '戏曲',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14588770636894.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14588720932562.jpg',
    'publishTime' => '2016-03-25',
    'score' => '8.0',
  ),
  20 => 
  array (
    'actor' => '徐立 / 曲少石 / 杨珑 / 刘著 / 刘金 / 曹蕾 / 李鹤楠 / 赵洪纪 / 李昕芮 / 王',
    'director' => '周阁',
    'has2D' => true,
    'hot' => 5,
    'hot_planCount' => 5,
    'hot_priority' => 0,
    'intro' => '　　云南一个美丽的小镇，几个刚毕业的大学生在某度假村酒店实习，这无疑是他们人生中最好的时期，但往往事与愿违……随着几个年轻人的到来，尘封已久的传说被开启，不可逆转的诅咒，使得平静的酒店再一次阴影笼罩，奇怪的敲击声，鲜红的血手印，种种的不寻常将所有人拉进幽怨的诅咒中。晓菲与 华子从此人鬼殊途，肥膘和老胡使得诅咒升级，柳姐亦不再冷静沉稳，夜夜惊声尖叫使得度假村瞬间成为鬼店。这一切究竟只是主人公的幻像还是已死之人死不瞑目？看似合理的故事背后却蕴含着让人不寒而栗的真相。',
    'minPrice' => '40.00',
    'minVipPrice' => '33.00',
    'movieId' => 387198,
    'movieLength' => 92,
    'movieName' => '别开门',
    'movieType' => '悬疑 / 惊悚',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14591430483334.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14586122912775.jpg',
    'publishTime' => '2016-05-13',
    'score' => '8.0',
  ),
  21 => 
  array (
    'actor' => '宋懿洁 / 蒋欣奇 / 张蓝艺 / 王燕阳 / 马丹旎 / 李艳冰 / 云翔 / 邓琳颖',
    'director' => '高育新 / 刘峰',
    'has2D' => true,
    'hot' => 5,
    'hot_planCount' => 10,
    'hot_priority' => 0,
    'intro' => '　　民国学生惊悚电影《笔仙诡影》近日发布笔魇女生版海报，正式定档2016年1月22日。影片取材民国时代灵异秘闻，历时七年筹备拍摄，耗费千万巨资修葺民国古宅，真实再现古老巫术笔仙。《笔仙诡影》由高育新、刘峰执导，宋懿洁、蒋欣奇 、张蓝艺、王燕阳、马丹旎、李艳冰、云翔、邓琳颖等新锐影星联袂出演。',
    'minPrice' => '40.00',
    'minVipPrice' => '33.00',
    'movieId' => 386614,
    'movieLength' => 90,
    'movieName' => '笔仙诡影',
    'movieType' => '悬疑 / 惊悚',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14598440044368.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14619120648888.jpg',
    'publishTime' => '2016-05-13',
    'score' => '8.0',
  ),
  22 => 
  array (
    'actor' => '陈柏霖 / 杨祐宁 / 蒋雯丽 / 秦沛 / 小茶',
    'director' => '忻钰坤 / 陈世杰 / 西瓦罗·孔萨库',
    'has2D' => true,
    'hot' => 4,
    'hot_planCount' => 2,
    'hot_priority' => 0,
    'intro' => '　　电影《再见，在也不见》由忻钰坤、陈世杰、西瓦罗·孔萨库联合执导，陈柏霖、蒋雯丽、杨祐宁、秦沛等两岸三地实力演员倾情演绎。电影讲述了一个关联的亲情，爱情，友情的情感故事。台湾文艺男神陈柏霖一人将人生所能经历的各种复杂情感体现的淋漓尽致。作为首部当选为台湾金马奖开幕影片的内地电影，该片着实令人期待。电影《再见，在也不见》也是新锐导演忻钰坤的最新力作。继《心迷宫》一炮而红后，忻钰坤以其冰冷写实的拍摄技巧以及细腻严谨的叙事风格获得了国内外影评人的一致盛赞。而这次参与《再见，在也不见》的联合指导，让人惊喜之余更大大提高了影片的期待值与关注度。',
    'minPrice' => '50.00',
    'minVipPrice' => '43.00',
    'movieId' => 387387,
    'movieLength' => 108,
    'movieName' => '再见，在也不见',
    'movieType' => '剧情 / 爱情 / 同性 / 家庭',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14585374186614.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14603593923167.jpg',
    'publishTime' => '2016-05-13',
    'score' => '8.0',
  ),
  23 => 
  array (
    'actor' => '何润东 / 李东学 / 夏梓桐 / 杨奇鸣 / 田原 / 赫子铭 / 宋宁 / 王往 / 黄天元',
    'director' => '阿甘',
    'has3D' => true,
    'hot' => 4,
    'hot_planCount' => 2,
    'hot_priority' => 0,
    'intro' => '　　哥哥王炳生（何润东 饰），弟弟陈铁金（李东学 饰），他们曾是相依为命、甘苦与共的兄弟。甚至哥哥炳生为弟弟铁金顶罪入狱十年，满身的伤疤与玩世不恭的态度是这十年的烙印，不变的却是兄弟之间的感情。不料在命运的捉弄下，两人在兵荒马乱的世界里失散，走上了不同的人生道路…… <br> 　　再度相逢时，曾经的患难兄弟已经势不两立。手足情深与家国信仰的冲突，令昔日兄弟成为生死之敌，最终展开了一场生死较量……',
    'minPrice' => '58.50',
    'minVipPrice' => '51.50',
    'movieId' => 386236,
    'movieLength' => 94,
    'movieName' => '钢刀',
    'movieType' => '剧情 / 动作',
    'pathHorizonH' => 'http://img.komovie.cn/activity/14488670476087.jpg',
    'pathVerticalS' => 'http://img.komovie.cn/poster/big/14586262223690.jpg',
    'publishTime' => '2016-05-20',
    'score' => '8.0',
  ),
);?>