<?php	return array (
  'actor' => '约翰尼·德普 / 米娅·华希科沃斯卡 / 安妮·海瑟薇 / 海伦娜·伯翰·卡特 / 马特·卢卡斯 /',
  'director' => '詹姆斯·博宾',
  'expired' => false,
  'has2D' => true,
  'has3D' => true,
  'hot' => 248,
  'hot_planCount' => 2427,
  'hot_priority' => 0,
  'intro' => '　　爱丽丝（米娅·华希科沃斯卡 Mia Wasikowska 饰）为了拯救挚友疯帽子（约翰尼·德普 Johnny Depp 饰）而重返仙境，她与白皇后（安妮·海瑟薇 Anne Hathaway 饰）及一群老朋友一起，展开了一段璀璨华美、永生难忘的奇幻冒险。然而除了邪恶的红皇后之外，爱丽丝还要面对另一位劲敌——时间（萨莎·拜伦·科恩 Sacha Baron Cohen 饰），他是传说中无人能击败的角色！爱丽丝要如何才能扭转乾坤，拯救疯帽子和仙境世界？ <br> 　　影片改编自路易斯·卡罗尔广受好评的同名原作。',
  'minPrice' => '30.00',
  'minVipPrice' => '28.00',
  'movieId' => 387704,
  'movieLength' => 108,
  'movieName' => '爱丽丝梦游仙境2：镜中奇遇记',
  'movieType' => '奇幻 / 冒险',
  'pathVerticalS' => 'http://img.komovie.cn/poster/big/14618256157011.jpg',
  'point' => 8,
  'publishTime' => '2016-05-27',
  'score' => '8.0',
);?>