<?php	return array (
  'actor' => '克里斯·埃文斯 / 小罗伯特·唐尼 / 斯嘉丽·约翰逊 / 塞巴斯蒂安·斯坦 / 安东尼·麦凯 / ',
  'director' => '安东尼·卢素 / 乔·卢素',
  'expired' => false,
  'has2D' => true,
  'has3D' => true,
  'hot' => 10182,
  'hot_planCount' => 1771,
  'hot_priority' => 200,
  'intro' => '　　美国队长史蒂夫·罗杰斯（克里斯·埃文斯 Chris Evans 饰）带领着全新组建的复仇者联盟，继续维护世界和平。然而，一次执行任务时联盟成员不小心造成大量平民伤亡，从而激发政治压力，政府决定通过一套监管系统来管理和领导复仇者联盟。联盟内部因此分裂为两派：一方由史蒂夫· 罗杰斯领导，他主张维护成员自由，在免受政府干扰的情况下保护世界；另一方则追随托尼·斯塔克（小罗伯特·唐尼 Robert Downey Jr. 饰），他令人意外地决定支持政府的监管和责任制体系。神秘莫测的巴基（塞巴斯蒂安·斯坦 Sebastian Stan 饰）似乎成为内战的关键人物……',
  'minPrice' => '28.00',
  'minVipPrice' => '25.90',
  'movieId' => 387351,
  'movieLength' => 148,
  'movieName' => '美国队长3测试环境改一下影片名称一会改回去不行还得再加点才行',
  'movieType' => '动作 / 科幻 / 冒险',
  'pathHorizonH' => 'http://img.komovie.cn/activity/14585373938960.jpg',
  'pathVerticalS' => 'http://img.komovie.cn/poster/big/14603590107231.jpg',
  'point' => 6,
  'publishTime' => '2016-05-06',
  'score' => '7.5',
);?>