<?php	return array (
  'actor' => '崔维斯·费米尔 / 本·福斯特 / 托比·凯贝尔 / 宝拉·巴顿 / 多米尼克·库珀 / 鲁丝·内伽',
  'director' => '邓肯·琼斯',
  'expired' => false,
  'has3D' => true,
  'hot' => 17,
  'hot_planCount' => 125,
  'hot_priority' => 0,
  'intro' => '　　根据暴雪娱乐公司的著名游戏改编，传奇影业的《魔兽》是一部空前紧张刺激的史诗历险巨制，由执导过《月球》和《源代码》的邓肯·琼斯编剧并导演。剧本由查尔斯·李维特（Charles Leavitt）共同编写。查尔斯·罗文（Charles Roven）、托马斯·图尔（Thomas Tull）、乔·贾希尼（Jon Jashni）和亚历克斯·加特纳（Alex Gartner）出任制片，斯图尔特·菲尼根（Stuart Fenegan）、吉莉安·谢尔（Jillian Share）和布兰特·欧康纳（Brent O’Connor）担任执行制片。',
  'minPrice' => '60.00',
  'minVipPrice' => '53.00',
  'movieId' => 18561,
  'movieLength' => 123,
  'movieName' => '魔兽',
  'movieType' => '动作 / 战争 / 奇幻 / 冒险',
  'pathHorizonH' => 'http://img.komovie.cn/activity/14610304358071.jpg',
  'pathVerticalS' => 'http://img.komovie.cn/poster/big/14624170423834.jpg',
  'point' => 7,
  'publishTime' => '2016-06-08',
  'score' => '6.0',
);?>