<?php
$data = array (
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '蛋糕',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '4',
    'name' => '蛋糕',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '好利来',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '7',
    'name' => '好利来',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '米卡米卡',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '8',
    'name' => '米卡米卡',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '诺心 • 蛋糕',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '61',
    'level' => 1,
    'id' => '5',
    'name' => '诺心 • 蛋糕',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '贝思客',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '9',
    'name' => '贝思客',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '味多美',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '6',
    'name' => '味多美',
  ),
);
?>